一、数组操作

min（返回数组中的最小值。）

In [1]:
import numpy as np
#示例1：array([1,1,2,3,3,4,5,6,6,2])
#示例2：array([0,1,2,3,3,4,5,6,6,2])
#示例3：array([2,2,2,3,3,4,5,6,6,2])
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.min(arr)

1

max（返回数组中的最大值。）

In [4]:
import numpy as np
#示例1：array([1,1,2,3,3,4,5,6,6,2])
#示例2：array([0,1,2,3,3,4,5,6,7,2])
#示例3：array([2,2,2,3,3,4,5,6,8,2])
arr = np.array([2,2,2,3,3,4,5,6,6,2])
np.max(arr)

6

unique(返回一个所有唯一元素排序的数组。)

return_counts:如果为True，返回数组中每个唯一元素出现的次数。

In [9]:
import numpy as np
#示例1：array([1,1,2,3,3,4,5,6,6,2])
#示例2：array([0,1,2,3,3,4,5,6,7,2])
#示例3：array([2,2,2,3,3,4,5,6,8,2])
arr = np.array([2,2,2,3,3,4,5,6,8,2])
np.unique(arr,return_counts=True)

(array([2, 3, 4, 5, 6, 8]), array([4, 2, 1, 1, 1, 1], dtype=int64))

mean(返回数组的平均数)



In [16]:
import numpy as np
#示例1：array([9,1,2,9,9,4,5,8,8,2])
#示例2：array([9,1,8,8,6,4,8,8,7,6])
#示例3：array([2,2,2,3,3,4,5,6,8,2])
arr = np.array([9,1,8,8,6,4,8,8,7,6])
np.mean(arr,dtype='int')

6

medain(返回数组的中位数。)


In [20]:
import numpy as np
#示例1：array([[1,2,3],[5,8,4]])
#示例2：array([[2,2,4],[5,8,4]])
#示例3：array([[1,2,7],[5,8,8]])
arr = np.array([[1,2,7],[5,8,8]])
np.median(arr)

6.0

reshape(NumPy中最常用的函数之一.返回一个数组，其中包含具有新形状的相同数据。)

In [24]:
import numpy as np
#示例1：arr.reshape(3,4)
#示例2：arr.reshape(4,3)
#示例3：arr.reshape(2,6)
arr = np.array([[8,14,1],
       [8,11,4],
       [9,4,1],
       [13,13,11]])
arr.reshape(4,3)

array([[ 8, 14,  1],
       [ 8, 11,  4],
       [ 9,  4,  1],
       [13, 13, 11]])

count_nonzero(计算所有非零元素并返回它们的计数。)

In [42]:
import numpy as np
#示例1：array([0,0,1,1,1,0])
#示例2：array([0,0,1,1,1,2])
#示例3：array([0,2,1,1,1,4])
a = np.array([0,2,1,1,1,4])
np.count_nonzero(a)

5

argwhere(查找并返回非零元素的所有下标。)

In [44]:
import numpy as np
#示例1：array([0,0,1,1,1,0])
#示例2：array([0,0,1,1,1,2])
#示例3：array([0,2,1,1,1,4])
a = np.array([0,2,1,1,1,4])
np.argwhere(a)

array([[1],
       [2],
       [3],
       [4],
       [5]], dtype=int64)

argmax & argmin

argmax返回数组中Max元素的索引。

In [47]:
import numpy as np
#示例1：([[8,7,6,5]])
#示例2：([[8,9,6,5]])
#示例3：([[2,4,6,5]])
arr = np.array([[2,4,6,5]])
np.argmax(arr)

2

argmin返回数组中min元素的索引。

In [49]:
import numpy as np
#示例1：([[8,7,3,5]])
#示例2：([[8,9,6,5]])
#示例3：([[2,4,6,5]])
arr = np.array([[8,7,3,5]])
np.argmin(arr)

2

sort(对数组排序)

In [51]:
import numpy as np
#示例1：([2,3,1,7,4,5])
#示例2：([11,20,15,7,4,5])
#示例3：([22,0,1,14,4,5])
arr = np.array([11,20,15,7,4,5])
np.sort(arr)

array([ 4,  5,  7, 11, 15, 20])

abs(返回数组中元素的绝对值。)

In [53]:
import numpy as np
#示例1：([[1,-3,4],[-2,-4,3]])
#示例2：([[-1,-3,-5],[-2,-4,3]])
#示例3：([[-9,-3,-8],[0,-6,3]])
A = np.array([[-1,-3,-5],[-2,-4,3]])
np.abs(A)

array([[1, 3, 5],
       [2, 4, 3]])

round(将浮点值四舍五入到指定数目的小数点。)
decimals:要保留的小数点的个数。

In [56]:
import numpy as np
a = np.random.random(size=(3,4))
a

array([[0.92674799, 0.56034082, 0.33166335, 0.11918572],
       [0.13863906, 0.90161266, 0.67286039, 0.05928157],
       [0.63174547, 0.78706624, 0.74231071, 0.01998786]])

In [58]:
#示例1：np.round(a,decimals=0)
#示例2：np.round(a,decimals=1)
#示例3：np.round(a,decimals=2)
np.round(a,decimals=1)

array([[0.9, 0.6, 0.3, 0.1],
       [0.1, 0.9, 0.7, 0.1],
       [0.6, 0.8, 0.7, 0. ]])

clip(它可以将数组的裁剪值保持在一个范围内。)

In [61]:
import numpy as np
arr = np.array([0,1,-3,-4,5,6,7,2,3])
#示例1：arr.clip(0,5)
#示例2：arr.clip(2,5)
#示例3：arr.clip(-3,0)
arr.clip(-3,0)

array([ 0,  0, -3, -3,  0,  0,  0,  0,  0])

二、替换数组中的值

where(返回满足条件的数组元素。)

In [64]:
import numpy as np
a = np.array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
#示例1：a[np.where(a>1)]
#示例2：a[np.where(a>3)]
#示例3：a[np.where(a>5)]
a[np.where(a>1)]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

put(用给定的值替换数组中指定的元素。)

In [67]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
#示例1：put(arr,[1,2],[6,7])
#示例2：put(arr,[1,3],[9,7])
#示例3：put(arr,[2,5],[6,7])
np.put(arr,[1,3],[9,7])#(arr,需要替换的索引，替换值）
arr

array([1, 9, 3, 7, 5, 6])

copyto(将一个数组的内容复制到另一个数组中。)

In [69]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([4,4,4])
#示例1：np.copyto(arr1,arr2)
#示例2：np.copyto(arr1,arr3)
#示例3：np.copyto(arr2,arr1)
np.copyto(arr1,arr3)#copyto(目标，来源)
print(arr1)

[4 4 4]
