## 集合操作
### 33. 查找公共元素

`intersect1d` 函数以排序的方式返回两个数组中都存在的唯一的值。
- **assume_unique**: 如果为真值，则假设输入数组中各个元素在该数组中都是唯一的。
- **return_indices**: 如果为真，则还返回公共元素在两个数组中的索引。



In [2]:
import numpy as np

In [10]:
#案例一
ar1 = np.array([1, 2, 2, 3, 4, 5, 6])
ar2 = np.array([3, 4, 4, 5, 8, 9, 1])
np.intersect1d(ar1,ar2)

array([1, 3, 4, 5])

In [13]:
#案例二
np.intersect1d(ar1,ar2,assume_unique=True)
#这个相当于告诉它每个数组中每个元素都是唯一的

array([1, 2, 3, 4, 4, 5])

In [12]:
#案例三
np.intersect1d(ar1,ar2,return_indices=True)

(array([1, 3, 4, 5]),
 array([0, 3, 4, 5], dtype=int64),
 array([6, 0, 1, 3], dtype=int64))

### 34. 查找不同元素

`np.setdiff1d` 函数返回 `arr1` 中存在，在 `arr2` 中不存在的所有唯一元素。


In [18]:
#案例一
a = np.array([1, 7, 3, 2, 4, 1])
b = np.array([9, 2, 5, 6, 7, 8])
np.setdiff1d(a, b)
#a-a ^ b

array([1, 3, 4])

In [3]:
#案例二
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 2, 3, 5, 3, 4])
np.setdiff1d(a, b)

array([1])

In [4]:
#案例三
a = np.array([1, 2, 3, 3, 4, 5])
b = np.array([9, 2, 5, 6, 7, 8])
np.setdiff1d(a, b)

array([1, 3, 4])

### 35. 从两个数组中提取唯一元素

`setxor1d` 将按顺序返回两个数组中所有唯一的值。


In [19]:
#案例一
a = np.array([1, 2, 3, 4, 6])
b = np.array([1, 4, 9, 4, 36])
np.setxor1d(a,b)


array([ 2,  3,  6,  9, 36])

In [5]:
#案例二
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 2, 3, 5, 3, 4])
np.setxor1d(a,b)

array([1, 5])

In [6]:
#案例三
a = np.array([1, 7, 3, 2, 4, 1])
b = np.array([9, 2, 5, 6, 7, 8])
np.setxor1d(a,b)

array([1, 3, 4, 5, 6, 8, 9])

### 36. 合并

`union1d` 函数将两个数组合并为一个,且自动除重。


In [20]:
#案例一
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 5, 4, 36])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5, 36])

In [7]:
#案例二
a = np.array([1, 7, 3, 2, 4, 1])
b = np.array([9, 2, 5, 6, 7, 8])
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#案例三
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 2, 3, 5, 3, 4])
np.union1d(a,b)

array([1, 2, 3, 4, 5])

## 数组分割
### 37. 水平分割

`hsplit` 函数将数据水平分割为 n 个相等的部分。


In [11]:
#案例一
A = np.array([[3,4,5,2],[6,7,2,6]])
B = np.array([[3,4,5,2],[6,7,2,6],[8,9,2,6]])
np.hsplit(A,2)   

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [12]:
#案例二
np.hsplit(B,2)

[array([[3, 4],
        [6, 7],
        [8, 9]]),
 array([[5, 2],
        [2, 6],
        [2, 6]])]

In [13]:
#案例三
np.hsplit(A,4)    

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

In [14]:
#案例四
np.hsplit(B,4)

[array([[3],
        [6],
        [8]]),
 array([[4],
        [7],
        [9]]),
 array([[5],
        [2],
        [2]]),
 array([[2],
        [6],
        [6]])]

### 38. 垂直分割

`vsplit` 将数据垂直分割为 n 个相等的部分。


In [16]:
#案例一
A = np.array([[3,4,5,2],[6,7,2,6]])
B = np.array([[3,4,5,2],[6,7,2,6],[8,9,2,6]])
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

In [18]:
#案例二
np.vsplit(B,3)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]]), array([[8, 9, 2, 6]])]

## 数组叠加
### 39. 水平叠加

`hstack` 将在另一个数组的末尾追加一个数组。


In [23]:
#案例一
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])

np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

### 40. 垂直叠加

`vstack` 将一个数组堆叠在另一个数组上。


In [24]:
#案例一
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [21]:
#案例二
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16])
np.vstack((a,b))
#列数不对称就会报错

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

## 数组比较
### 41. allclose

如果两个数组的形状相同，则 `allclose` 函数根据公差值查找两个数组是否相等或近似相等。


In [35]:
#案例一
a = np.array([0.25,0.4,0.6,0.32])
b = np.array([0.26,0.3,0.7,0.32])

tolerance = 0.1           ## 公差值
np.allclose(a,b,atol=tolerance)
#∣a−b∣≤(atol+rtol×∣b∣) 相对公差
# 默认的rtol 值为 1e-05

False

In [33]:
#案例二
tolerance = 0.5
np.allclose(a,b,tolerance)

True

### 42. equal

它比较两个数组的每个元素，如果元素匹配就返回 True。


In [38]:
#案例一
np.equal(a,b)


array([False, False, False,  True])

## 重复的数组元素
### repeat

它用于重复数组中的元素 n 次。

- **A**: 重复的元素
- **Repeats**: 重复的次数。


In [39]:
#案例一
np.repeat('2024',4)

array(['2024', '2024', '2024', '2024'], dtype='<U4')

In [40]:
#案例二
import pandas as pd

fruits = pd.DataFrame([
    ['Mango',40],
    ['Apple',90],
    ['Banana',130]
],columns=['Product','ContainerSales'])
fruits

Product  ContainerSales
0   Mango              40
1   Apple              90
2  Banana             130

In [42]:
fruits['year'] = np.repeat(2024,fruits.shape[0])
fruits

Product  ContainerSales  year
0   Mango              40  2024
1   Apple              90  2024
2  Banana             130  2024

### 43. tile

通过重复 A，rep 次来构造一个数组。


In [44]:
#案例一
np.tile("Ramm",5)

array(['Ramm', 'Ramm', 'Ramm', 'Ramm', 'Ramm'], dtype='<U4')

In [45]:
#案例二
np.tile(3,(2,3))

array([[3, 3, 3],
       [3, 3, 3]])

## 爱因斯坦求和
### 44. einsum

此函数用于计算数组上的多维和线性代数运算。


In [52]:
#案例一
a = np.arange(1,10).reshape(3,3)
b = np.arange(21,30).reshape(3,3)
np.einsum('ij',a)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
#案例二
np.einsum('ij',b)


array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [55]:
#案例三
np.einsum('ii->i',a)

15

In [47]:
#案例四
np.einsum('ji',a)


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
#案例五
np.einsum('ij,jk',a,b)

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [49]:
#案例六
np.einsum('ii',a)

15

## 统计分析
### 45. 直方图

这是 Numpy 的重要统计分析函数，可计算一组数据的直方图值。


In [56]:
#案例一
A = np.array([[3, 4, 5, 2],
              [6, 7, 2, 6]])
np.histogram(A)

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1], dtype=int64),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))

### 46. 百分位数

沿指定轴计算数据的 Q-T-T 百分位数。

- **a**: 输入。
- **q**: 要计算的百分位。
- **overwrite_input**: 如果为 true，则允许输入数组修改中间计算以节省内存。


In [57]:
#案例一
a = np.array([[2, 4, 6], [4, 8, 12]])

np.percentile(a, 50)

5.0

In [58]:
#案例二
np.percentile(a, 10)

3.0

In [61]:
#案例三
arr = np.array([2,3,4,1,6,7])
np.percentile(arr,5)

1.25

### 47. 标准偏差和方差

`std` 和 `var` 是 NumPy 的两个函数，用于计算每轴的标准偏差和方差。


In [72]:
#案例一
a = np.array([[2, 4, 6], [4, 8, 12]])
np.mean(a,axis=0)

array([3., 6., 9.])

In [62]:
#案例二
np.std(a,axis=1)

array([1.63299316, 3.26598632])

In [63]:
#案例三
np.std(a,axis=0)    ## Column Wise

array([1., 2., 3.])

In [64]:
#案例四
np.var(a,axis=1)

array([ 2.66666667, 10.66666667])

In [65]:
#案例五
np.var(a,axis=0)

array([1., 4., 9.])