创建数组

1、Array

它用于创建一维或多维数组

Dtype:生成数组所需的数据类型。

ndim:指定生成数组的最小维度数。

还可以使用此函数将pandas的df和series转为NumPy数组

In [10]:
#案例一：
import numpy as np
np.array([1, 2, 3, 4, 5], dtype=int)

array([1, 2, 3, 4, 5])

In [6]:
#案例二：
import numpy as np
np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]], dtype=float)

array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6]])

In [7]:
#案例三：
import numpy as np
np.array([1, 2, 3, 4, 5], dtype=int, ndmin=2)

array([[1, 2, 3, 4, 5]])

In [8]:
#案例四：
import numpy as np
import pandas as pd
series = pd.Series([1, 2, 3, 4, 5])
np.array(series, dtype=int)

array([1, 2, 3, 4, 5])

In [9]:
#案例五：
import numpy as np
import pandas as pd
sex = pd.Series(['Male','Male','Female'])
np.array(sex)

array(['Male', 'Male', 'Female'], dtype=object)

2、Linspace

创建一个具有指定间隔的浮点数的数组。

start:起始数字

stop:结束

Num:要生成的样本数，默认为50。

endpoint：是否包含stop

In [11]:
#案例一：
import numpy as np
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [12]:
#案例二：
import numpy as np
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
#案例三：
import numpy as np
np.linspace(start=0, stop=1, num=5, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [14]:
#案例四：
import numpy as np
np.linspace(start=0, stop=10, num=100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [5]:
#案例五：
import numpy as np
np.linspace(start=0, stop=5, num=10, dtype=int)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 5])

3、Arange

在给定的间隔内返回具有一定步长的整数。

step:数值步长。

In [18]:
#案例一：
import numpy as np
np.arange(start=0, stop=10, step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#案例二：
import numpy as np
np.arange(start=0, stop=10, step=2)

array([0, 2, 4, 6, 8])

In [20]:
#案例三：
import numpy as np
np.arange(start=0, stop=5, step=0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [21]:
#案例四：
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#案例五：
import numpy as np
np.arange(start=10, stop=0, step=-1)


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

4、Uniform

在上下限之间的均匀分布中生成随机浮点样本。

In [23]:
#案例一：
import numpy as np
np.random.uniform(5,10,size = 4)

array([8.5577744 , 5.50962113, 8.02133   , 5.38917727])

In [24]:
#案例二：
import numpy as np
np.random.uniform(low=0, high=1, size=10)

array([0.06151951, 0.73939128, 0.90021152, 0.59982478, 0.34932506,
       0.77421187, 0.04471531, 0.03242115, 0.50248118, 0.49619498])

In [25]:
#案例三：
import numpy as np
np.random.uniform(low=10, high=20,size=5)

array([10.12329247, 13.9860093 , 10.23066576, 10.57884951, 17.73032217])

In [26]:
#案例四：
import numpy as np
np.random.uniform(low=0, high=1, size=(2, 3))

array([[0.60606358, 0.16410718, 0.97373444],
       [0.27779845, 0.31379895, 0.39769246]])

In [27]:
#案例五
import numpy as np
np.random.uniform(low=0, high=1, size=10).astype(np.float32)

array([0.31772316, 0.8392374 , 0.06477372, 0.8505104 , 0.7205376 ,
       0.41196764, 0.00973955, 0.07904109, 0.46365184, 0.07842513],
      dtype=float32)

5、Random.randint

在一个范围内生成n个随机整数样本。

In [7]:
#案例一：
import numpy as np
np.random.randint(low=0, high=10, size=10)

array([5, 7, 5, 4, 5, 2, 6, 6, 3, 3])

In [36]:
#案例二：
import numpy as np
np.random.randint(5,10,10)

array([7, 9, 8, 8, 7, 6, 8, 5, 9, 8])

In [8]:
#案例三：
import numpy as np
np.random.randint(low=10, high=20, size=5)

array([11, 13, 12, 11, 15])

In [9]:
#案例四：
import numpy as np
np.random.randint(low=0, high=10, size=(2, 3))

array([[0, 5, 5],
       [4, 2, 3]])

In [10]:
#案例五
import numpy as np
np.random.randint(low=0, high=100, size=10, dtype=np.int64)

array([ 0, 32,  2, 10, 60, 17, 88, 71, 52, 31], dtype=int64)

6、Random.random

生成n个随机浮点数样本。

In [28]:
#案例一：
import numpy as np
np.random.random(3)

array([0.12749267, 0.17826973, 0.40211397])

In [29]:
#案例二：
import numpy as np
np.random.random(size=10)

array([0.62104209, 0.86023494, 0.05261119, 0.02474002, 0.65003101,
       0.98106905, 0.08559897, 0.99616897, 0.21901664, 0.68651523])

In [30]:
#案例三：
import numpy as np
np.random.random(size=(2, 3))

array([[0.51310539, 0.08821681, 0.8013598 ],
       [0.90180511, 0.34332236, 0.86127284]])

In [31]:
#案例四：
import numpy as np
np.random.random(size=10).astype(np.float32)

array([0.06677254, 0.92618877, 0.59992415, 0.5458168 , 0.32241404,
       0.8853617 , 0.9983558 , 0.33345416, 0.8624311 , 0.85267025],
      dtype=float32)

In [32]:
#案例五
import numpy as np
np.random.random(size=(3, 4, 2))

array([[[0.02545074, 0.27152338],
        [0.72223428, 0.47910145],
        [0.72319113, 0.38878473],
        [0.59368584, 0.83838974]],

       [[0.11169552, 0.92206856],
        [0.18117456, 0.06458484],
        [0.82555811, 0.44952524],
        [0.15008678, 0.70653511]],

       [[0.11440089, 0.48686014],
        [0.6856027 , 0.00974028],
        [0.8560694 , 0.63963227],
        [0.57800926, 0.5876622 ]]])

7、Logspace

在对数尺度上生成间隔均匀的数字。

Start:序列的起始值。

stop:序列的最后一个值。

endpoint:如果为True，最后一个样本将包含在序列中。

base:底数。默认是10。

输出结果：(科学记数：1.e + 02 此格式用指数表示法显示数字，以 E+n 替换部分数字，其中 E（代表指数）表示将前面的数字1乘以 10 的 2 次幂。)

In [33]:
#案例一：
import numpy as np
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

In [34]:
#案例二：
import numpy as np
np.logspace(start=1, stop=3, num=10, endpoint=False)

array([ 10.        ,  15.84893192,  25.11886432,  39.81071706,
        63.09573445, 100.        , 158.48931925, 251.18864315,
       398.10717055, 630.95734448])

In [35]:
#案例三：
import numpy as np
np.logspace(start=1, stop=3, num=10, base=2)

array([2.        , 2.33305808, 2.72158   , 3.1748021 , 3.70349885,
       4.32023896, 5.0396842 , 5.87893797, 6.85795186, 8.        ])

In [36]:
#案例四：
import numpy as np
np.logspace(start=0, stop=2, num=5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [37]:
#案例五
import numpy as np
np.logspace(start=1, stop=3, num=9).reshape((3, 3))

array([[  10.        ,   17.7827941 ,   31.6227766 ],
       [  56.23413252,  100.        ,  177.827941  ],
       [ 316.22776602,  562.34132519, 1000.        ]])

8、zeroes

np.zeroes会创建一个全部为0的数组。

shape:阵列的形状。

Dtype:生成数组所需的数据类型。' int '或默认' float '

In [38]:
#案例一：
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
#案例二：
import numpy as np
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [40]:
#案例三：
import numpy as np
np.zeros(shape=(2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
#案例四：
import numpy as np
np.zeros(shape=5, dtype=int)

array([0, 0, 0, 0, 0])

In [42]:
#案例五：
import numpy as np
np.zeros(shape=(2, 2, 2, 2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

9、ones

np.ones函数创建一个全部为1的数组。

In [ ]:
#案例一：
import numpy as np
np.ones(shape=5)

In [47]:
#案例二：
import numpy as np
np.ones(shape=(2, 3))

In [47]:
#案例三：
import numpy as np
np.ones(shape=(2, 3, 4))

In [47]:
#案例四：
import numpy as np
np.ones(shape=5, dtype=int)

In [47]:
#案例五
import numpy as np
np.ones(shape=(2, 2, 2, 2))

10、full

创建一个单独值的n维数组。

fill_value:填充值。

In [43]:
#案例一：
import numpy as np
np.full(shape=5, fill_value=7)

array([7, 7, 7, 7, 7])

In [44]:
#案例二：
import numpy as np
np.full(shape=(2, 3), fill_value=9.5)

array([[9.5, 9.5, 9.5],
       [9.5, 9.5, 9.5]])

In [45]:
#案例三：
import numpy as np
np.full(shape=(2, 2), fill_value=5, dtype=int)

array([[5, 5],
       [5, 5]])

In [46]:
#案例四：
import numpy as np
np.full(shape=(2, 3, 4), fill_value=0.1)

array([[[0.1, 0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1, 0.1]],

       [[0.1, 0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1, 0.1]]])

In [47]:
#案例五
import numpy as np
np.full(shape=(2, 2, 2, 2), fill_value=3.14, dtype=np.float32)

array([[[[3.14, 3.14],
         [3.14, 3.14]],

        [[3.14, 3.14],
         [3.14, 3.14]]],


       [[[3.14, 3.14],
         [3.14, 3.14]],

        [[3.14, 3.14],
         [3.14, 3.14]]]], dtype=float32)

11、Identity

创建具有指定维度的单位矩阵。

In [50]:
#案例一：
import numpy as np
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
#案例二：
import numpy as np
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
#案例三：
import numpy as np
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
#案例四：
import numpy as np
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [54]:
#案例五
import numpy as np
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

数组打印

12、显示带有两个十进制值的浮点数

In [55]:
#案例一：
import numpy as np
np.array([2.71828, 1.61803], dtype=np.float64)

array([2.71828, 1.61803])

In [56]:
#案例二：
import numpy as np
np.float64(3.1415926)

3.14159

In [57]:
#案例三：
import numpy as np
np.set_printoptions(precision=2)
np.array([12.23456,32.34535])

array([12.23, 32.35])

In [58]:
#案例四：
import numpy as np
np.array([123.456, 789.012], dtype=np.float64)

array([123.46, 789.01])

In [59]:
#案例五
import numpy as np
np.float64(42.195)

42.195

13、设置打印数组最大值

1.precision：控制输出结果的精度(即小数点后的位数)，默认值为8

2.threshold：当数组元素总数过大时，设置显示的数字位数，其余用省略号代替(当数组元素总数大于设置值，控制输出值得个数为6个，当数组元素小于或者等于设置值得时候，全部显示)，当设置值为sys.maxsize(需要导入sys库)，则会输出所有元素

3.linewidth：每行字符的数目，其余的数值会换到下一行

4.suppress：小数是否需要以科学计数法的形式输出

5.formatter：自定义输出规则


In [16]:
#案例一：
import numpy as np
large_array=np.arange(1000)
np.set_printoptions(threshold=10)
print(large_array)

[  0   1   2 ... 997 998 999]


In [12]:
#案例二：
import numpy as np
large_array1=np.random.rand(20, 20)
np.set_printoptions(threshold=50)
print(large_array1)

[[0.67108346 0.25321803 0.23436241 ... 0.69589533 0.65479413 0.99400431]
 [0.93953996 0.77738851 0.60642363 ... 0.52866966 0.20957357 0.56593268]
 [0.91531092 0.76734211 0.25919655 ... 0.12614619 0.45589702 0.36855938]
 ...
 [0.94876455 0.5125252  0.06527825 ... 0.17306328 0.1641852  0.4652182 ]
 [0.99469201 0.23390469 0.52118314 ... 0.81617045 0.80827711 0.11088867]
 [0.85952212 0.48016947 0.48398149 ... 0.30400677 0.7326576  0.46003656]]


In [65]:
#案例三：
import numpy as np
large_array = np.arange(100)
np.set_printoptions(threshold=100)
print(large_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [66]:
#案例四：
import numpy as np
large_array = np.random.rand(20, 20)
np.set_printoptions(threshold=50, precision=4)
print(large_array)

[[0.8232 0.1533 0.4216 ... 0.5875 0.5037 0.9042]
 [0.2687 0.7628 0.4534 ... 0.8324 0.384  0.8905]
 [0.0715 0.274  0.3722 ... 0.4269 0.1951 0.0873]
 ...
 [0.8781 0.2176 0.0795 ... 0.0511 0.3847 0.0407]
 [0.0053 0.7786 0.591  ... 0.3293 0.4868 0.0927]
 [0.7238 0.4175 0.2369 ... 0.2476 0.293  0.9834]]


In [67]:
#案例五
import numpy as np
large_array = np.random.rand(10, 10)
np.set_printoptions(threshold=5, linewidth=100)
print(large_array)

[[0.2015 0.3529 0.743  ... 0.0449 0.5527 0.7161]
 [0.2769 0.6233 0.3702 ... 0.4737 0.5652 0.4154]
 [0.8395 0.293  0.3147 ... 0.5817 0.4395 0.8705]
 ...
 [0.1866 0.1001 0.7026 ... 0.3649 0.3171 0.5424]
 [0.6822 0.2524 0.1664 ... 0.5014 0.5889 0.8025]
 [0.3722 0.917  0.653  ... 0.7326 0.8024 0.4639]]


14、数组简单操作

In [17]:
#案例一：
import numpy as np
original_array = np.array([[1, 2, 3]])
resized_array = np.resize(original_array, (2, 5))
print("原始数组:")
print(original_array)
print("调整后的数组:")
print(resized_array)

原始数组:
[[1 2 3]]
调整后的数组:
[[1 2 3 1 2]
 [3 1 2 3 1]]


In [18]:
#案例二：
import numpy as np
original_array = np.array([[1, 2, 3]])
new_array = np.zeros_like(original_array)
new_array[0, :] = original_array
print("原始数组:")
print(original_array)
print("新数组:")
print(new_array)

原始数组:
[[1 2 3]]
新数组:
[[1 2 3]]


In [70]:
#案例三：
import numpy as np
original_array = np.array([[1, 2, 3]])
new_row = np.array([[4, 5, 6]])
concatenated_array = np.concatenate((original_array, new_row), axis=0)
print("原始数组:")
print(original_array)
print("连接后的数组:")
print(concatenated_array)

原始数组:
[[1 2 3]]
连接后的数组:
[[1 2 3]
 [4 5 6]]


In [71]:
#案例四：
import numpy as np
original_array = np.array([[1, 2, 3]])
padded_array = np.pad(original_array, ((0, 1), (0, 0)), mode='constant', constant_values=0)
print("原始数组:")
print(original_array)
print("填充后的数组:")
print(padded_array)

原始数组:
[[1 2 3]]
填充后的数组:
[[1 2 3]
 [0 0 0]]


In [72]:
#案例五
import numpy as np
original_array = np.array([[1, 2, 3]])
new_row = np.array([4, 5, 6])
extended_array = np.array([np.append(row, new_row) for row in original_array])
print("原始数组:")
print(original_array)
print("扩展后的数组:")
print(extended_array)

原始数组:
[[1 2 3]]
扩展后的数组:
[[1 2 3 4 5 6]]


保存和加载数据

15、保存

In [20]:
#案例一：
import numpy as np
original_array = np.array([[1, 2, 3]])
resized_array = np.resize(original_array, (2, 5))
np.save('resized_array.npy', resized_array)

In [74]:
#案例二：
import numpy as np
original_array = np.array([[1, 2, 3]])
new_row = np.array([4, 5, 6])
extended_array = np.array([np.append(row, new_row) for row in original_array])
np.savetxt('extended_array.txt', extended_array, fmt='%d', delimiter='')

In [75]:
#案例三：
import numpy as np
original_array = np.array([[1, 2, 3],[4, 5, 6]])
resized_array = np.resize(original_array, (3, 4))
np.save('resized_array.npy', resized_array)

In [76]:
#案例四：
import numpy as np
float_array = np.array([[1.234, 2.345, 3.456],[4.567, 5.678, 6.789]])
np.savetxt('float_array.txt', float_array, fmt='%.2f', delimiter='')

In [77]:
#案例五
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([[4, 5, 6],[7, 8, 9]])
np.savez('arrays.npz', array1=array1, array2=array2)

16、加载

In [78]:
#案例一：
import numpy as np
loaded_array = np.load('resized_array.npy')
print("加载的数组:")
print(loaded_array)

加载的数组:
[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]


In [79]:
#案例二：
import numpy as np
loaded_array = np.loadtxt('extended_array.txt', delimiter=',')
print("加载的数组:")
print(loaded_array)

加载的数组:
123456.0


In [80]:
#案例三：
import numpy as np
npzfile = np.load('arrays.npz')
array1 = npzfile['array1']
array2 = npzfile['array2']
print("加载的数组 array1:")
print(array1)
print("\n加载的数组 array2:")
print(array2)

加载的数组 array1:
[1 2 3]

加载的数组 array2:
[[4 5 6]
 [7 8 9]]
