一、数组操作

17.min（返回数组中的最小值。）

In [1]:
#示例1：array([1,1,2,3,3,4,5,6,6,2])
import numpy as np
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.min(arr)

1

In [1]:
#示例2：array([0,1,2,3,3,4,5,6,6,2])
import numpy as np
arr = np.array([0,1,2,3,3,4,5,6,6,2])
np.min(arr)

0

In [2]:
#示例3：array([2,2,2,3,3,4,5,6,6,2])
import numpy as np
arr = np.array([2,2,2,3,3,4,5,6,6,2])
np.min(arr)

2

18.max（返回数组中的最大值。）

In [5]:
#示例1：array([1,1,2,3,3,4,5,6,6,2])
import numpy as np
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.max(arr)

6

In [3]:
#示例2：array([0,1,2,3,3,4,5,6,7,2])
import numpy as np
arr = np.array([0,1,2,3,3,4,5,6,7,2])
np.max(arr)

7

In [4]:
#示例3：array([2,2,2,3,3,4,5,6,8,2])
import numpy as np
arr = np.array([2,2,2,3,3,4,5,6,8,2])
np.max(arr)

8

19.unique(返回一个所有唯一元素排序的数组。)

return_counts:如果为True，返回数组中每个唯一元素出现的次数。

In [6]:
#示例1：array([1,1,2,3,3,4,5,6,6,2])
import numpy as np
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 1, 1, 2], dtype=int64))

In [7]:
#示例2：array([0,1,2,3,3,4,5,6,7,2])
import numpy as np
arr = np.array([0,1,2,3,3,4,5,6,7,2])
np.unique(arr,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([1, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

In [8]:
#示例3：array([2,2,2,3,3,4,5,6,8,2])
import numpy as np
arr = np.array([2,2,2,3,3,4,5,6,8,2])
np.unique(arr,return_counts=True)

(array([2, 3, 4, 5, 6, 8]), array([4, 2, 1, 1, 1, 1], dtype=int64))

20.mean(返回数组的平均数)



In [16]:
#示例1：array([9,1,2,9,9,4,5,8,8,2])
import numpy as np
arr = np.array([9,1,2,9,9,4,5,8,8,2])
np.mean(arr,dtype='int')

6

In [9]:
#示例2：array([9,1,8,8,6,4,8,8,7,6])
import numpy as np
arr = np.array([9,1,8,8,6,4,8,8,7,6])
np.mean(arr,dtype='int')

6

In [10]:
#示例3：array([2,2,2,3,3,4,5,6,8,2])
import numpy as np
arr = np.array([2,2,2,3,3,4,5,6,8,2])
np.mean(arr,dtype='int')

3

21.medain(返回数组的中位数。)


In [11]:
#示例1：array([[1,2,3],[5,8,4]])
import numpy as np
arr = np.array([[1,2,3],[5,8,4]])
np.median(arr)

3.5

In [12]:
#示例2：array([[2,2,4],[5,8,4]])
import numpy as np
arr = np.array([[2,2,4],[5,8,4]])
np.median(arr)

4.0

In [13]:
#示例3：array([[1,2,7],[5,8,8]])
import numpy as np
arr = np.array([[1,2,7],[5,8,8]])
np.median(arr)

6.0

22.reshape(NumPy中最常用的函数之一.返回一个数组，其中包含具有新形状的相同数据。)

In [14]:
#示例1：arr.reshape(3,4)
import numpy as np
arr = np.array([[8,14,1],
       [8,11,4],
       [9,4,1],
       [13,13,11]])
arr.reshape(3,4)

array([[ 8, 14,  1,  8],
       [11,  4,  9,  4],
       [ 1, 13, 13, 11]])

In [15]:
#示例2：arr.reshape(4,3)
import numpy as np
arr = np.array([[8,14,1],
       [8,11,4],
       [9,4,1],
       [13,13,11]])
arr.reshape(4,3)

array([[ 8, 14,  1],
       [ 8, 11,  4],
       [ 9,  4,  1],
       [13, 13, 11]])

In [16]:
#示例3：arr.reshape(2,6)
import numpy as np
arr = np.array([[8,14,1],
       [8,11,4],
       [9,4,1],
       [13,13,11]])
arr.reshape(2,6)

array([[ 8, 14,  1,  8, 11,  4],
       [ 9,  4,  1, 13, 13, 11]])

23.count_nonzero(计算所有非零元素并返回它们的计数。)

In [17]:
#示例1：array([0,0,1,1,1,0])
import numpy as np
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

3

In [18]:
#示例2：array([0,0,1,1,1,2])
import numpy as np
a = np.array([0,0,1,1,1,2])
np.count_nonzero(a)

4

In [19]:
#示例3：array([0,2,1,1,1,4])
import numpy as np
a = np.array([0,2,1,1,1,4])
np.count_nonzero(a)

5

24.argwhere(查找并返回非零元素的所有下标。)

In [20]:
#示例1：array([0,0,1,1,1,0])
import numpy as np
a = np.array([0,0,1,1,1,0])
np.argwhere(a)

array([[2],
       [3],
       [4]], dtype=int64)

In [21]:
#示例2：array([0,0,1,1,1,2])
import numpy as np
a = np.array([0,0,1,1,1,2])
np.argwhere(a)

array([[2],
       [3],
       [4],
       [5]], dtype=int64)

In [22]:
#示例3：array([0,2,1,1,1,4])
import numpy as np
a = np.array([0,2,1,1,1,4])
np.argwhere(a)

array([[1],
       [2],
       [3],
       [4],
       [5]], dtype=int64)

25.argmax & argmin

argmax返回数组中Max元素的索引。

In [23]:
#示例1：([[8,7,6,5]])
import numpy as np
arr = np.array([[8,7,6,5]])
np.argmax(arr)

0

In [24]:
#示例2：([[8,9,6,5]])
import numpy as np
arr = np.array([[8,9,6,5]])
np.argmax(arr)

1

In [25]:
#示例3：([[2,4,6,5]])
import numpy as np
arr = np.array([[2,4,6,5]])
np.argmax(arr)

2

argmin返回数组中min元素的索引。

In [49]:
import numpy as np
#示例1：([[8,7,3,5]])
#示例2：([[8,9,6,5]])
#示例3：([[2,4,6,5]])
arr = np.array([[8,7,3,5]])
np.argmin(arr)

2

26.sort(对数组排序)

In [26]:
#示例1：([2,3,1,7,4,5])
import numpy as np
arr = np.array([2,3,1,7,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

In [27]:
#示例2：([11,20,15,7,4,5])
import numpy as np
arr = np.array([11,20,15,7,4,5])
np.sort(arr)

array([ 4,  5,  7, 11, 15, 20])

In [28]:
#示例3：([22,0,1,14,4,5])
import numpy as np
arr = np.array([22,0,1,14,4,5])
np.sort(arr)

array([ 0,  1,  4,  5, 14, 22])

27.abs(返回数组中元素的绝对值。)

In [29]:
#示例1：([[1,-3,4],[-2,-4,3]])
import numpy as np
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

In [30]:
#示例2：([[-1,-3,-5],[-2,-4,3]])
import numpy as np
A = np.array([[-1,-3,-5],[-2,-4,3]])
np.abs(A)

array([[1, 3, 5],
       [2, 4, 3]])

In [31]:
#示例3：([[-9,-3,-8],[0,-6,3]])
import numpy as np
A = np.array([[-9,-3,-8],[0,-6,3]])
np.abs(A)

array([[9, 3, 8],
       [0, 6, 3]])

28.round(将浮点值四舍五入到指定数目的小数点。)
decimals:要保留的小数点的个数。

In [32]:
import numpy as np
a = np.random.random(size=(3,4))
a

array([[0.6522835 , 0.19529387, 0.68000104, 0.9397523 ],
       [0.73117254, 0.7758192 , 0.26925321, 0.70156831],
       [0.41146812, 0.04938538, 0.77374017, 0.96196697]])

In [33]:
#示例1：np.round(a,decimals=0)
#示例2：np.round(a,decimals=1)
#示例3：np.round(a,decimals=2)
np.round(a,decimals=0)

array([[1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [0., 0., 1., 1.]])

In [34]:
#示例2：np.round(a,decimals=1)
np.round(a,decimals=1)

array([[0.7, 0.2, 0.7, 0.9],
       [0.7, 0.8, 0.3, 0.7],
       [0.4, 0. , 0.8, 1. ]])

In [35]:
#示例3：np.round(a,decimals=2)
np.round(a,decimals=2)

array([[0.65, 0.2 , 0.68, 0.94],
       [0.73, 0.78, 0.27, 0.7 ],
       [0.41, 0.05, 0.77, 0.96]])

29.clip(将数组的裁剪值保持在一个范围内。)

In [36]:
#示例1：arr.clip(0,5)
import numpy as np
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [37]:
#示例2：arr.clip(2,5)
import numpy as np
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(2,5)

array([2, 2, 2, 2, 5, 5, 5, 2, 3])

In [38]:
#示例3：arr.clip(-3,0)
import numpy as np
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(-3,0)

array([ 0,  0, -3, -3,  0,  0,  0,  0,  0])

二、替换数组中的值

30.where(返回满足条件的数组元素。)

In [39]:
#示例1：a[np.where(a>1)]
import numpy as np
a = np.array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
a[np.where(a>1)]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
#示例2：a[np.where(a>3)]
import numpy as np
a = np.array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
a[np.where(a>3)]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
#示例3：a[np.where(a>5)]
import numpy as np
a = np.array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
a[np.where(a>5)]

array([ 6,  7,  8,  9, 10, 11])

31.put(用给定的值替换数组中指定的元素。)

In [42]:
#示例1：put(arr,[1,2],[6,7])
import numpy as np
arr = np.array([1,2,3,4,5,6])
np.put(arr,[1,2],[6,7])#(arr,需要替换的索引，替换值）
arr

array([1, 6, 7, 4, 5, 6])

In [43]:
#示例2：put(arr,[1,3],[9,7])
import numpy as np
arr = np.array([1,2,3,4,5,6])
np.put(arr,[1,3],[9,7])#(arr,需要替换的索引，替换值）
arr

array([1, 9, 3, 7, 5, 6])

In [44]:
#示例3：put(arr,[2,5],[6,7])
import numpy as np
arr = np.array([1,2,3,4,5,6])
np.put(arr,[2,5],[6,7])#(arr,需要替换的索引，替换值）
arr

array([1, 2, 6, 4, 5, 7])

32.copyto(将一个数组的内容复制到另一个数组中。)

In [61]:
#示例1：np.copyto(arr1,arr2)
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([4,4,4])
np.copyto(arr1,arr2)#copyto(目标，来源)
print(arr1)

[4 5 6]


In [62]:
#示例2：np.copyto(arr1,arr3)
import numpy as np
np.copyto(arr1,arr3)#copyto(目标，来源)
print(arr1)

[4 4 4]


In [63]:
#示例3：np.copyto(arr2,arr1)
import numpy as np
np.copyto(arr2,arr1)#copyto(目标，来源)
print(arr2)

[4 4 4]
